Added category CRUD, rack CRUD already completed
ChrisWilhelm/MathForABetterWorld pull request #22
Opened 2023-02-25 16:36 UTC by krutalp

2023-02-25 23:20 UTC, ChrisWilhelm requested changes

2023-02-25 23:20 UTC, ChrisWilhelm commented on server/src/controller/categoryController.js
> +        id,
you never got the id field from the request

2023-02-25 23:20 UTC, ChrisWilhelm commented on server/src/routes/category.js
> +    param("id", "Must include id in the body").notEmpty().isInt(),
if id is going to be a param, then you need to add /:id to the URL

2023-02-25 23:20 UTC, ChrisWilhelm commented on server/src/util/categoryMiddleware.js
> +  if (query !== NULL) {
lowercase null

2023-02-25 23:20 UTC, ChrisWilhelm commented on server/src/util/categoryMiddleware.js
> +    if (query === NULL || query === undefined) {
lowercase null

2023-02-25 23:35 UTC, jstelnik approved these changes

2023-02-25 23:35 UTC, jstelnik commented on server/src/routes/category.js
> +    body("name", "Must include unique name for category").notEmpty(),
maybe also do description body comment, even though not super necessary. 

body('description', 'Description is a string').optional().isString(),

2023-02-27 21:31 UTC, ChrisWilhelm requested changes

2023-02-27 21:31 UTC, ChrisWilhelm commented on server/src/routes/category.js
> +    "/update",
you need to combine the urls, to be like "/update/:id" or "/:id/update"

2023-02-28 16:06 UTC, ChrisWilhelm approved these changes

2023-02-28 16:06 UTC, merged